package fpt.edu.common;

public enum PageType {
	USER_MANAGERMENT_PAGE,
	REPORT_MANAGERMENT_PAGE,
	VIDEO_MANAGERMENT_PAGE,
	
	SITE_HOME_PAGE,
	SITE_LOGIN_PAGE,
	SITE_REGISTRATION_PAGE,
	SITE_CHANGEPASSWORD_PAGE,
	SITE_FORGOTPASSWORD_PAGE,
	SITE_EDITPROFILE_PAGE,
	
	SITE_VIDEO_DETAIL_PAGE,
	SITE_VIDEO_FAVORITE_PAGE,
	SITE_VIDEO_SHARE_PAGE,
	SITE_VIDEO_SEARCH_PAGE
}
